-- AlterTable
ALTER TABLE "ApiKey" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ USING "createdAt" AT TIME ZONE 'UTC',
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ USING "updatedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "Contract" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ USING "createdAt" AT TIME ZONE 'UTC',
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ USING "updatedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "Environment" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ USING "createdAt" AT TIME ZONE 'UTC',
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ USING "updatedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "Org" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ USING "createdAt" AT TIME ZONE 'UTC',
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ USING "updatedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "OrgInvite" ALTER COLUMN "tokenExpiresAt" SET DATA TYPE TIMESTAMPTZ USING "tokenExpiresAt" AT TIME ZONE 'UTC',
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ USING "createdAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "OrgMember" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ USING "createdAt" AT TIME ZONE 'UTC',
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ USING "updatedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "Project" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ USING "createdAt" AT TIME ZONE 'UTC',
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ USING "updatedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "Team" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ USING "createdAt" AT TIME ZONE 'UTC',
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ USING "updatedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "TeamMember" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ USING "createdAt" AT TIME ZONE 'UTC',
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ USING "updatedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "TeamProject" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ USING "createdAt" AT TIME ZONE 'UTC',
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ USING "updatedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ USING "createdAt" AT TIME ZONE 'UTC',
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ USING "updatedAt" AT TIME ZONE 'UTC';

-- AlterTable
ALTER TABLE "UserAction" ALTER COLUMN "actionTimestamp" SET DATA TYPE TIMESTAMPTZ USING "actionTimestamp" AT TIME ZONE 'UTC';
