// behavioral errors (non-500s) must be added to this
// set and have their HTTP code chosen in mapError
// TODO consider prefixing errors by module name or a global prefix
export enum UserError {
  SERVER_ERROR = 'SERVER_ERROR',
  PERMISSION_DENIED = 'PERMISSION_DENIED',
  BAD_ORG = 'BAD_ORG',
  MISSING_ORG_NAME = 'MISSING_ORG_NAME',
  ORG_INVITE_BAD_TOKEN = 'ORG_INVITE_BAD_TOKEN',
  ORG_INVITE_DUPLICATE = 'ORG_INVITE_DUPLICATE',
  ORG_INVITE_EMAIL_MISMATCH = 'ORG_INVITE_EMAIL_MISMATCH',
  ORG_INVITE_EXPIRED = 'ORG_INVITE_EXPIRED',
  ORG_INVITE_ALREADY_MEMBER = 'ORG_INVITE_ALREADY_MEMBER',
  BAD_ORG_PERSONAL = 'BAD_ORG_PERSONAL',
  ORG_FINAL_ADMIN = 'ORG_FINAL_ADMIN',
  BAD_USER = 'BAD_USER',
  NAME_CONFLICT = 'NAME_CONFLICT',
  BAD_ORG_INVITE = 'BAD_ORG_INVITE',
}
