name: Build Project
on:
  pull_request:
    branches: [development]
jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install Nest.js
        run: npm i -g @nestjs/cli

      - name: Install dependencies
        run: npm ci

      - name: Build Prisma Client
        run: npx prisma generate --schema ./src/core

      - name: Test building a project
        run: npm run build
