name: Build Project
on:
  pull_request:
    branches: [development]
jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm i

      - name: Install Nest.js
        run: npm i -g @nestjs/cli

      - name: Test building a project
        run: npm run build
