environment                  = "dev"
namespace                    = "dev"
frontend_base_url            = "https://core.dev.console.pagoda.co"
ems_vpc_access_connector     = "projects/pagoda-shared-infrastructure/locations/us-east1/connectors/dev-connector1"
ems_provisioning_service_url = "http://ems-provisioning.dev.gcp.pagoda.co"
