FROM mcr.microsoft.com/playwright:v1.23.1-focal

WORKDIR /app

# By splitting this out from copying everything, docker should be able to cache node_modules if the package and lock files haven't changed.
COPY package.json .
COPY package-lock.json .
RUN npm ci
RUN npx playwright install

COPY . .

# exit 0 will allow the tests to fail and the docker image to be built and tagged for later.
RUN npm run test:e2e; exit 0