/* tslint:disable */
/* eslint-disable */
/**
 * Endpoints as a Service Provisiong Service (epaas-ps)
 * This is the documentation for the Endpoint as a Service Provisioning Service system. 
 *
 * OpenAPI spec version: 0.0.1
 * Contact: will@near.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ConsumerNameList
 */
export interface ConsumerNameList {
    /**
     * List of names of all KongConsumer objects on the cluster
     * @type {Array<string>}
     * @memberof ConsumerNameList
     */
    consumer_names?: Array<string>;
}
