/* tslint:disable */
/* eslint-disable */
/**
 * Endpoints as a Service Provisiong Service (epaas-ps)
 * This is the documentation for the Endpoint as a Service Provisioning Service system. 
 *
 * OpenAPI spec version: 0.0.1
 * Contact: will@near.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DeleteObjectDetails } from './delete-object-details';
/**
 * 
 * @export
 * @interface DeleteObject
 */
export interface DeleteObject {
    /**
     * 
     * @type {DeleteObjectDetails}
     * @memberof DeleteObject
     */
    details?: DeleteObjectDetails;
    /**
     * 
     * @type {string}
     * @memberof DeleteObject
     */
    kind?: string;
    /**
     * 
     * @type {string}
     * @memberof DeleteObject
     */
    status?: string;
}
