/* tslint:disable */
/* eslint-disable */
/**
 * Endpoints as a Service Provisiong Service (epaas-ps)
 * This is the documentation for the Endpoint as a Service Provisioning Service system. 
 *
 * OpenAPI spec version: 0.0.1
 * Contact: will@near.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SecretBody
 */
export interface SecretBody {
    /**
     * Additional ID field used for further linking with external systems
     * @type {string}
     * @memberof SecretBody
     */
    kongCredType: SecretBodyKongCredTypeEnum;
    /**
     * Name that makes logical sense for use in your service
     * @type {string}
     * @memberof SecretBody
     */
    name: string;
}

/**
    * @export
    * @enum {string}
    */
export enum SecretBodyKongCredTypeEnum {
    KeyAuth = 'key-auth'
}

