name: Build Project
on:
  pull_request:
    branches: [develop, module, release, main]
jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install Nest.js
        run: npm i -g @nestjs/cli

      - name: Install dependencies
        run: npm ci

      - name: Test building a project
        run: npx turbo build --filter=backend --force
        # remove --force when we are confident in turbo caching configuration
        # since it can significantly speed up Action execution

      - name: Run unit tests
        run: npm -w backend run test
