# Frontend changes will automatically deploy via the vercel git integration.
name: Deploy a develop environment
on:
  pull_request:
    branches: [develop]
defaults:
  run:
    working-directory: backend
jobs:
  deploy-image:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/terraform
    env:
      VERCEL_PROJECT_NAME: developer-console-framework-prod
      VERCEL_ORG: near
      VERCEL_TEAM_ID: team_0XCkE3xOywBTMmd6s7bqJQot
      GIT_REPO: pagoda-console
    steps:
      - uses: actions/checkout@v3
      
      - name: "Set env variables"
        run: |
          echo "DEV_NAMESPACE=dev" >> $GITHUB_ENV
          echo "DEV_SERVICE_NAME=developer-console-api-test" >> $GITHUB_ENV
          echo "DEV_REGION=us-east1" >> $GITHUB_ENV
          echo "DEV_DB_URL=35.185.74.37" >> $GITHUB_ENV
          echo "DEV_IMAGE_URL=gcr.io/near-dev-platform/developer-console-api:dev" >> $GITHUB_ENV

      - name: "Perform DB migrations"
        run: |
          pwd && cd .. && \
          DB_USER=postgres DB_PASS=${{secrets.DATABASE_PASSWORD_DEVELOP}} DB_URL=$DEV_DB_URL . ./scripts/export_prisma_env_vars.sh && \
          cd .. && pwd && npm ci && npm run -w database migrate:deploy
