# TODO this workflow only needs to run when the PR is initially opened or the backend/ changes.
# Frontend changes will automatically deploy via the vercel git integration.
name: Deploy a preview environment
on:
  #* This workflow expects to be ran on pull requests only. Push and other triggers may not result in a successful run.
  pull_request:
    branches: [develop]
defaults:
  run:
    working-directory: backend
jobs:
  namespace:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    outputs:
      namespace: ${{ steps.namespace.outputs.namespace }}
    steps:
      - id: "namespace"
        name: "Build namespace from Git branch name"
        run: |
          echo GITHUB_REF $GITHUB_REF 
          echo GITHUB_HEAD_REF $GITHUB_HEAD_REF

          # PREVIEW_NAMESPACE is intended to be small and unique and is composed of:
          # The first 10 chars in the github branch name after the last '/' followed by
          # the first 5 chars in the sha256 of the whole branch name.
          export BRANCH_NAME=$(echo -n ${GITHUB_HEAD_REF##*/} | cut -c -10)
          export BRANCH_SHA=$(echo -n $GITHUB_HEAD_REF | sha256sum | cut -c -5)
          export PREVIEW_NAMESPACE="${BRANCH_NAME}-${BRANCH_SHA}"
          echo PREVIEW_NAMESPACE $PREVIEW_NAMESPACE

          echo "::set-output name=namespace::$PREVIEW_NAMESPACE"

  docker-build-and-push:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    needs: [namespace]
    outputs:
      image: ${{ steps.image.outputs.image }}
    steps:
      - uses: actions/checkout@v2

      # Setup auth: https://github.com/google-github-actions/setup-gcloud#service-account-key-json
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"

      - name: "Use gcloud CLI"
        run: gcloud auth configure-docker -q

      - name: "Set namespace"
        run: echo "PREVIEW_NAMESPACE=${{ needs.namespace.outputs.namespace }}" >> $GITHUB_ENV

      # Last line of this script is the docker image url with the sha256 hash that
      # was uploaded. This should be used in terraform so that we can deploy a new
      # cloud run instance if the docker image has changed.
      - name: Build docker image and push
        run: ./scripts/docker_build_and_push.sh ${PREVIEW_NAMESPACE} developer-platform-dev

      - id: image
        name: "Outputs docker image with registry's sha256"
        run: |
          export API_IMAGE=$(docker inspect --format='{{index .RepoDigests 0}}' gcr.io/developer-platform-dev/developer-console-api:$PREVIEW_NAMESPACE)
          echo "::set-output name=image::$API_IMAGE"

  terraform-preview-environment:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    needs: [namespace, docker-build-and-push]
    defaults:
      run:
        working-directory: backend/terraform
    env:
      VERCEL_PROJECT_NAME: developer-console-framework-prod
      VERCEL_ORG: near
      VERCEL_TEAM_ID: team_0XCkE3xOywBTMmd6s7bqJQot
      GIT_REPO: pagoda-console
      BRANCH_NAME: ${GITHUB_HEAD_REF}
      VERCEL_AUTH_TOKEN: ${{ secrets.VERCEL_AUTH_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2

      # Setup auth: https://github.com/google-github-actions/setup-gcloud#service-account-key-json
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"

      - name: "Set namespace"
        run: echo "PREVIEW_NAMESPACE=${{ needs.namespace.outputs.namespace }}" >> $GITHUB_ENV

      - name: Terraform Workspace
        run: |
          terraform workspace new preview-$PREVIEW_NAMESPACE
          terraform workspace select preview-$PREVIEW_NAMESPACE

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Apply
        run: |
          # TODO move this step to the beginning and set DOWNTIME_MODE=maintenance so it's clear that the preview env is being updated with a new backend and db.
          export FRONTEND_BASE_URL=$(../scripts/vercel_redeploy.sh)

          echo FRONTEND_BASE_URL $FRONTEND_BASE_URL

          terraform apply -input=false -var-file ./env/preview.tfvars \
            -var "namespace=${PREVIEW_NAMESPACE}" \
            -var "database_password=${{secrets.DATABASE_PASSWORD_PREVIEW}}" \
            -var "api_image=${{needs.docker-build-and-push.outputs.image}}" \
            -var "frontend_base_url=${FRONTEND_BASE_URL}" \
            -var "api_service_account=${{secrets.API_SERVICE_ACCOUNT_PREVIEW}}"

      - name: Vercel deploy with API URL
        run: |
          export API_BASE_URL=$(terraform output -raw api_public_url)

          # Set an env var for this branch's preview environment
          ../scripts/vercel_upsert_env_var.sh NEXT_PUBLIC_API_BASE_URL $API_BASE_URL

          ../scripts/vercel_redeploy.sh
