name: Destroy a preview environment
on:
  pull_request:
    types: [closed]
    branches: [develop]
defaults:
  run:
    working-directory: backend
jobs:
  namespace:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    outputs:
      namespace: ${{ steps.namespace.outputs.namespace }}
    steps:
      - id: "namespace"
        name: "Build namespace from Git branch name"
        run: |
          echo GITHUB_REF $GITHUB_REF 
          echo GITHUB_HEAD_REF $GITHUB_HEAD_REF

          # PREVIEW_NAMESPACE is intended to be small and unique and is composed of:
          # The first 10 chars in the github branch name after the last '/' followed by
          # the first 5 chars in the sha256 of the whole branch name.
          export BRANCH_NAME=$(echo -n ${GITHUB_HEAD_REF##*/} | cut -c -10)
          export BRANCH_SHA=$(echo -n $GITHUB_HEAD_REF | sha256sum | cut -c -5)
          export PREVIEW_NAMESPACE="${BRANCH_NAME}-${BRANCH_SHA}"
          echo PREVIEW_NAMESPACE $PREVIEW_NAMESPACE

          echo "::set-output name=namespace::$PREVIEW_NAMESPACE"

  destroy-preview-environment:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    needs: [namespace]
    defaults:
      run:
        working-directory: backend/terraform
    env:
      VERCEL_PROJECT_NAME: developer-console-framework-prod
      VERCEL_ORG: near
      VERCEL_TEAM_ID: team_0XCkE3xOywBTMmd6s7bqJQot
      GIT_REPO: pagoda-console
      BRANCH_NAME: ${GITHUB_HEAD_REF}
      VERCEL_AUTH_TOKEN: ${{ secrets.VERCEL_AUTH_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2

      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"

      - name: "Set namespace"
        run: echo "PREVIEW_NAMESPACE=${{ needs.namespace.outputs.namespace }}" >> $GITHUB_ENV

      - name: Terraform Destroy
        run: |
          export TF_WORKSPACE=preview-$PREVIEW_NAMESPACE
          terraform init -input=false
          terraform destroy -input=false -var-file ./env/preview.tfvars \
            -var "namespace=${PREVIEW_NAMESPACE}" \
            -var "database_password=${{secrets.DATABASE_PASSWORD_PREVIEW}}" \
            -var "api_image=${{needs.docker-build-and-push.outputs.image}}" \
            -var "frontend_base_url=destroy" \
            -var "api_service_account=${{secrets.API_SERVICE_ACCOUNT_PREVIEW}}"

          # TODO make sure this deletes the TF state file from GCP bucket.
          # Delete this unneeded workspace
          terraform workspace select default
          terraform workspace delete $TF_WORKSPACE

      # TODO do we need to destroy any GCP or Vercel secrets?
