name: E2E Tests
on:
  push:
    branches: [develop]
  # You could test this CI job in a PR by uncommenting the below pull_request line.
  # pull_request:
  #   branches: [develop]
defaults:
  run:
    working-directory: frontend
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run e2e tests
        run: npm run test:e2e
        env:
          TEST_URL: https://core.dev.console.pagoda.co
          TEST_EMAIL: jon+e2e@near.org
          TEST_PASSWORD: ${{ secrets.E2E_TEST_ACCOUNT_PASSWORD }}
          TEST_CREATE_BLANK_PROJECT: "My Cool Project for E2E Testing"
          TEST_CREATE_NFT_TUTORIAL_PROJECT: "My Cool NFT Project for E2E Testing"
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 14
